# Generated by Django 4.0.5 on 2022-06-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_mediafile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='format',
            field=models.CharField(choices=[('l-in', 'Left Inline'), ('r-in', 'Right Inline'), ('c-full', 'Center Full Screen')], max_length=6),
        ),
    ]
